name: Daily Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'  # runs daily at 06:00 UTC (adjust as needed)

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run daily parse & predict
        run: |
          DATE=$(date +%F)
          python3 pipeline/parse_forms.py --date "$DATE"
          python3 analysis/predict.py --date "$DATE" --top 1
      - name: Upload picks artifact
        uses: actions/upload-artifact@v4
        with:
          name: picks
          path: out/picks_$(date +%F).csv
