name: Run Greyhound Analysis

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pandas matplotlib

    - name: Run analysis
      run: |
        python greyhound_analysis.py

    - name: Upload recommended bets
      uses: actions/upload-artifact@v3
      with:
        name: recommended-bets
        path: recommended_bets.csv

    - name: Upload ROI table
      uses: actions/upload-artifact@v3
      with:
        name: roi-table
        path: roi_table.csv

    - name: Upload speed by distance
      uses: actions/upload-artifact@v3
      with:
        name: speed-by-distance
        path: speed_by_distance.csv

    - name: Upload box performance chart
      uses: actions/upload-artifact@v3
      with:
        name: box-performance-chart
        path: box_performance.png
